# Generated by Django 3.2.4 on 2022-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundAssayResults',
            fields=[
                ('compound_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('molecular_weight', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundInfo',
            fields=[
                ('compound_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('molecular_weight', models.CharField(max_length=100)),
                ('ALogP', models.CharField(max_length=50)),
                ('molecular_formula', models.TextField(max_length=50)),
                ('num_rings', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
